- job:
    name: heatclient-functional
    parent: legacy-dsvm-base
    run: playbooks/devstack/functional-run.yaml
    post-run: playbooks/devstack/functional-post.yaml
    timeout: 4200
    required-projects:
      - openstack/devstack-gate
      - openstack/heat
      - openstack/python-heatclient
    vars:
      branch_override: default

- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
      - openstackclient-plugin-jobs
      - publish-openstack-sphinx-docs
      - release-notes-jobs
    check:
      jobs:
        - heatclient-functional
    gate:
      jobs:
        - heatclient-functional
    post:
      jobs:
        - openstack-tox-cover
